# Generated by Django 2.2.10 on 2021-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('tech', 'TECH'), ('angular', 'ANGULAR'), ('reactjs', 'REACTJS'), ('ui/ux', 'UI/UX')], default='examupdate', max_length=120)),
                ('mini_description', models.CharField(max_length=120)),
            ],
        ),
    ]
