# Generated by Django 2.2.10 on 2021-06-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobileno', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.CharField(max_length=120)),
            ],
        ),
    ]
