# Generated by Django 2.2.10 on 2021-06-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapsi', '0002_registrationapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_company', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('mobileno', models.CharField(max_length=120)),
                ('service', models.CharField(max_length=220)),
                ('start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('account_details', models.TextField()),
                ('payment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_company', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('mobileno', models.CharField(max_length=120)),
                ('service', models.CharField(max_length=220)),
                ('qutation_cost', models.CharField(max_length=120)),
                ('process', models.CharField(choices=[('not talk', 'NOT TALK'), ('pending', 'PENDING'), ('confirmed', 'CONFIRMED')], default='not talk', max_length=120)),
            ],
        ),
    ]
