# Generated by Django 2.2.10 on 2021-07-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapsi', '0004_auto_20210702_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientform',
            name='phone',
        ),
    ]
